version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@possword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-net

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin@password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "7070:80"
    depends_on:
      - postgres
    networks:
      - postgres-net

networks:
  postgres-net:

volumes:
  postgres-data:
  pgadmin-data:
